<h1><?php echo $this->getHelloWorldTxt(); ?></h1>
<style>
    .flex-container {
        display: flex;
        flex-wrap: wrap;
        width: 100%;
    }

    .box {
        box-shadow: 2px 2px 2px 0px #222;
        flex: 1;
        width: 100%;
        min-width: 20vmin;
        box-shadow: 0 2px 3px 0 rgba(0,0,0,.14),0 3px 2px -2px rgba(0,0,0,.2),0 1px 5px 0 rgba(0,0,0,.12);
        margin: 2vmin 4vmin 2vmin 4vmin;
        padding: 2vmin;
        cursor: pointer;
        text-align: center;
        transition: 0.2s transform;
    }

    .box:hover {
        transform: scale(1.1);
    }

    .box img {
        margin-left: auto;
        margin-right: auto;
        display: block;
    }
</style>
<div class="flex-container">
    <?php
    $products = $this->getProductsData();

    foreach ($products as $product) {
        #$product = $products[$len];
        $color = $product->getResource()->getAttribute('color')->getFrontend()->getValue($product);
        if ($color === "Red") {
            echo "<div class='box'>";
            $productImageUrl = $this->getUrl('pub/media/catalog').'product'.$product->getImage();
            echo "<img width='100px' src='$productImageUrl'>";
            echo "<br><p>".$product->getName()."</p>";
            echo "</div>\n";
        }
    }
    /*
    $class_methods = get_class_methods($product);
$this->getProductBySku("MH02-XS-Red"); // load product by SKU

    foreach ($class_methods as $method_name) {
        echo "<br> $method_name ";
    }
    */

    ?>
</div>